# Generated by Django 4.2.6 on 2024-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('content', models.CharField(max_length=5000, verbose_name='Description')),
                ('price', models.IntegerField(default=0)),
                ('devise', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamier_name', models.CharField(default='mon panier', max_length=128, null=True)),
            ],
        ),
    ]
