# Generated by Django 4.2.6 on 2024-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='articles',
        ),
        migrations.AddField(
            model_name='panier',
            name='products',
            field=models.ManyToManyField(to='article.article'),
        ),
    ]
