# Generated by Django 4.2.6 on 2024-01-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_panier_alter_panier_pamier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='panier',
            field=models.ForeignKey(default='mon panier', on_delete=django.db.models.deletion.DO_NOTHING, to='article.panier'),
        ),
    ]
