# Generated by Django 4.2.6 on 2024-01-14 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_alter_article_panier_alter_panier_pamier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='pamier_name',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='panier_user',
        ),
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='LinePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.panier')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='article',
            field=models.ManyToManyField(through='article.LinePanier', to='article.article'),
        ),
    ]
