# Generated by Django 4.2.6 on 2024-01-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_category_options_remove_article_panier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='article',
            new_name='articles',
        ),
    ]
