# Generated by Django 4.2.6 on 2023-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone_number_alter_user_friends_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pick',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
